[package]
name = "node-api-sys"
version = "0.1.0"
authors = ["Jupp MÃ¼ller <jupp0r@gmail.com>"]
license = "MIT"
description = "Bindings for nodejs NAPI"
homepage = "https://github.com/jupp0r/node-api-sys"

[dependencies]
